# Generated by Django 3.1 on 2020-08-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_schooluser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schooluser',
        ),
    ]
